# Generated by Django 4.0.1 on 2022-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(choices=[('Existant', 'Existant'), ('Potentiel', 'Potentiel')], max_length=20),
        ),
        migrations.DeleteModel(
            name='ClientStatus',
        ),
    ]
